import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Figtree } from "next/font/google";
import { Nunito } from "next/font/google";
import { Young_Serif } from "next/font/google";
import { Space_Mono } from "next/font/google";

//Figtree font definition
const figtree = Figtree({
  subsets: ["latin"],
  style: ["normal"],
  variable: "--font-figtree",
});

//Space_mono font definition
const spaceMono = Space_Mono({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["700"],
  variable: "--font-space_mono",
});

//Nunito font definition
const nunito = Nunito({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["700"],
  variable: "--font-nunito",
});

//Young_Serif font definition
const youngSerif = Young_Serif({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-young_serif",
  style: ["normal"],
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Open Enterprise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${nunito.variable} ${figtree.variable} ${spaceMono.variable} ${youngSerif.variable}`}>
      <head>
        <link rel="icon" href="./favicon.ico" />
      </head>
      <body className="bg-[#F9F9F9]">{children}</body>
    </html>
  );
}
