import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Young_Serif } from "next/font/google";
import { Figtree } from "next/font/google";

//Young_Serif font definition
const youngSerif = Young_Serif({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-Young_Serif",
});

//Figtree font definition
const figTree = Figtree({
  subsets: ["latin"],
  style: ["normal"],
  variable: "--font-figtree",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "OE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${figTree.variable} ${youngSerif.variable}`}>
      <body>{children}</body>
    </html>
  );
}
